Update the egui source hash is Cargo.toml
Without this, `cargo build` fails with:

    error: failed to get `egui` as a dependency of package `demo_glium v0.1.0 (/home/data/go/src/github.com/emilk/emigui/demo_glium)`

    Caused by:
      failed to load source for dependency `egui`

    Caused by:
      Unable to update https://github.com/emilk/emigui#e3d1d6c9

    Caused by:
      revspec 'e3d1d6c99ce37090d496b4f210aaef700235dd9b' not found; class=Reference (4); code=NotFound (-3)

Looks like that particular commit was removed from github. This change
is a result of removing the packages referencing the hash form
`Cargo.lock` and re-running `cargo build`.