Revert "cargo update"
This reverts commit 174c938d18fce75feb5618ca14bd62e5f553e7e1.

This is because some dependency stopped wasm-bindgen with the following message:

    error: cannot import from modules (`env`) with `--no-modules`

and I don't want to spend the rest of the evening figuring out why